if(NOT DEFINED OUTPUT)
  message(FATAL_ERROR "OUTPUT not set")
endif()
if(NOT DEFINED UI_BUILD_TAG OR UI_BUILD_TAG STREQUAL "")
  string(TIMESTAMP _ts "UI_BUILD_%Y-%m-%d_%H%M%S")
  string(RANDOM LENGTH 6 ALPHABET "0123456789ABCDEF" _rand)
  set(UI_BUILD_TAG "${_ts}_${_rand}")
endif()
if(DEFINED UI_BUILD_TAG_FILE)
  get_filename_component(_tag_dir "${UI_BUILD_TAG_FILE}" DIRECTORY)
  file(MAKE_DIRECTORY "${_tag_dir}")
  file(WRITE "${UI_BUILD_TAG_FILE}" "${UI_BUILD_TAG}")
endif()
file(WRITE ${OUTPUT} " #pragma once\n")
file(APPEND ${OUTPUT} " #define UI_BUILD_TAG \"${UI_BUILD_TAG}\"\n")
