#!/usr/bin/env python3
import argparse
from pathlib import Path
import uharfbuzz as hb
import freetype

ASCII = "ascii"


def shape_text(font_path: Path, text: str, size_px: int):
    font_data = font_path.read_bytes()
    face = freetype.Face(str(font_path))
    face.set_pixel_sizes(0, size_px)

    hb_face = hb.Face(font_data)
    hb_font = hb.Font(hb_face)
    hb_font.scale = (face.size.x_ppem << 6, face.size.y_ppem << 6)
    hb.ot_font_set_funcs(hb_font)

    buf = hb.Buffer()
    buf.add_str(text)
    buf.guess_segment_properties()
    hb.shape(hb_font, buf, {})

    infos = buf.glyph_infos
    positions = buf.glyph_positions

    pen_x = 0
    pen_y = 0
    glyphs = []

    for info, pos in zip(infos, positions):
        glyph_index = info.codepoint
        x_offset = pos.x_offset >> 6
        y_offset = pos.y_offset >> 6
        x_advance = pos.x_advance >> 6
        y_advance = pos.y_advance >> 6

        face.load_glyph(glyph_index, freetype.FT_LOAD_RENDER | freetype.FT_LOAD_TARGET_NORMAL)
        bitmap = face.glyph.bitmap
        glyphs.append({
            "bitmap": bitmap,
            "left": face.glyph.bitmap_left,
            "top": face.glyph.bitmap_top,
            "x": pen_x + x_offset + face.glyph.bitmap_left,
            "y": pen_y - y_offset - face.glyph.bitmap_top,
        })

        pen_x += x_advance
        pen_y += y_advance

    if not glyphs:
        return None

    min_x = min(g["x"] for g in glyphs)
    min_y = min(g["y"] for g in glyphs)
    max_x = max(g["x"] + g["bitmap"].width for g in glyphs)
    max_y = max(g["y"] + g["bitmap"].rows for g in glyphs)

    width = max_x - min_x
    height = max_y - min_y

    bitmap = [[0 for _ in range(width)] for _ in range(height)]

    for g in glyphs:
        bmp = g["bitmap"]
        for row in range(bmp.rows):
            for col in range(bmp.width):
                val = bmp.buffer[row * bmp.pitch + col]
                if val > 0:
                    xx = g["x"] - min_x + col
                    yy = g["y"] - min_y + row
                    if 0 <= xx < width and 0 <= yy < height:
                        bitmap[yy][xx] = 1

    return width, height, bitmap


def pack_bitmap(width: int, height: int, bitmap):
    row_bytes = (width + 7) // 8
    data = bytearray(row_bytes * height)
    for y in range(height):
        for x in range(width):
            if bitmap[y][x]:
                idx = y * row_bytes + (x >> 3)
                data[idx] |= (0x80 >> (x & 7))
    return data


def emit_header(name: str, width: int, height: int, data: bytes, out_path: Path):
    lines = []
    lines.append("// Auto-generated by tools/gen_devanagari_bitmap.py")
    lines.append("#pragma once")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append(f"#define {name.upper()}_WIDTH {width}")
    lines.append(f"#define {name.upper()}_HEIGHT {height}")
    lines.append("")
    lines.append(f"static const uint8_t {name}_bitmap[] = {{")
    line = "    "
    for i, val in enumerate(data):
        line += f"0x{val:02X}, "
        if (i + 1) % 12 == 0:
            lines.append(line.rstrip())
            line = "    "
    if line.strip():
        lines.append(line.rstrip())
    lines.append("};")
    lines.append("")
    out_path.write_text("\n".join(lines) + "\n", encoding=ASCII)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--font", required=True)
    parser.add_argument("--text", required=True)
    parser.add_argument("--size", type=int, required=True)
    parser.add_argument("--name", default="devanagari_text")
    parser.add_argument("--out", required=True)
    args = parser.parse_args()

    font_path = Path(args.font)
    shaped = shape_text(font_path, args.text, args.size)
    if shaped is None:
        raise SystemExit("No glyphs rendered")
    width, height, bitmap = shaped
    data = pack_bitmap(width, height, bitmap)
    emit_header(args.name, width, height, data, Path(args.out))


if __name__ == "__main__":
    main()
