#!/usr/bin/env python3
import argparse
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

ASCII_START = 32
ASCII_END = 126


def render_glyphs(font_path: Path, size: int):
    font = ImageFont.truetype(str(font_path), size=size)
    ascent, descent = font.getmetrics()
    height = ascent + descent

    space_width = int(round(font.getlength(" ")))
    if space_width <= 0:
        space_width = max(1, size // 4)

    bitmaps = bytearray()
    offsets = []
    widths = []

    for code in range(ASCII_START, ASCII_END + 1):
        ch = chr(code)
        offsets.append(len(bitmaps))
        if ch == " ":
            widths.append(space_width)
            row_bytes = (space_width + 7) // 8
            bitmaps.extend(b"\x00" * (row_bytes * height))
            continue

        bbox = font.getbbox(ch, anchor="ls")
        x0, y0, x1, y1 = bbox
        width = max(1, x1 - x0)

        img = Image.new("1", (width, height), 1)  # 1 = white
        draw = ImageDraw.Draw(img)
        # Anchor baseline at y=ascent, shift x to align left
        draw.text((-x0, ascent), ch, font=font, fill=0, anchor="ls")

        row_bytes = (width + 7) // 8
        for y in range(height):
            row_bits = 0
            for x in range(width):
                if img.getpixel((x, y)) == 0:
                    row_bits |= (1 << (7 - (x & 7)))
                if (x & 7) == 7 or x == width - 1:
                    bitmaps.append(row_bits & 0xFF)
                    row_bits = 0

        widths.append(width)

    return {
        "size": size,
        "height": height,
        "ascent": ascent,
        "descent": descent,
        "space_width": space_width,
        "bitmaps": bitmaps,
        "offsets": offsets,
        "widths": widths,
    }


def emit_header(fonts, out_path: Path):
    def emit_array_u8(name, data):
        lines = []
        lines.append(f"static const uint8_t {name}[] = {{")
        line = "    "
        for i, val in enumerate(data):
            line += f"0x{val:02X}, "
            if (i + 1) % 12 == 0:
                lines.append(line.rstrip())
                line = "    "
        if line.strip():
            lines.append(line.rstrip())
        lines.append("};")
        return "\n".join(lines)

    def emit_array_u16(name, data):
        lines = []
        lines.append(f"static const uint16_t {name}[] = {{")
        line = "    "
        for i, val in enumerate(data):
            line += f"{val}, "
            if (i + 1) % 10 == 0:
                lines.append(line.rstrip())
                line = "    "
        if line.strip():
            lines.append(line.rstrip())
        lines.append("};")
        return "\n".join(lines)

    out = []
    out.append("// Auto-generated by tools/gen_roboto_font.py")
    out.append("#pragma once")
    out.append("#include <stdint.h>")
    out.append("")
    out.append("typedef struct {")
    out.append("    uint8_t size;")
    out.append("    uint8_t height;")
    out.append("    uint8_t ascent;")
    out.append("    uint8_t descent;")
    out.append("    uint8_t space_width;")
    out.append("    const uint8_t *bitmaps;")
    out.append("    const uint16_t *offsets;")
    out.append("    const uint8_t *widths;")
    out.append("} roboto_font_t;")
    out.append("")

    for f in fonts:
        size = f["size"]
        out.append(emit_array_u8(f"roboto_{size}_bitmaps", f["bitmaps"]))
        out.append("")
        out.append(emit_array_u16(f"roboto_{size}_offsets", f["offsets"]))
        out.append("")
        out.append(emit_array_u8(f"roboto_{size}_widths", f["widths"]))
        out.append("")
        out.append(
            "static const roboto_font_t roboto_{size} = {{ .size = {size}, .height = {height}, .ascent = {ascent}, .descent = {descent}, .space_width = {space_width}, .bitmaps = roboto_{size}_bitmaps, .offsets = roboto_{size}_offsets, .widths = roboto_{size}_widths }};".format(
                size=size,
                height=f["height"],
                ascent=f["ascent"],
                descent=f["descent"],
                space_width=f["space_width"],
            )
        )
        out.append("")

    out_path.write_text("\n".join(out) + "\n", encoding="ascii")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--font", required=True)
    parser.add_argument("--sizes", nargs="+", type=int, required=True)
    parser.add_argument("--out", required=True)
    args = parser.parse_args()

    font_path = Path(args.font)
    fonts = [render_glyphs(font_path, size) for size in args.sizes]
    emit_header(fonts, Path(args.out))


if __name__ == "__main__":
    main()
