#!/usr/bin/env python3
"""
analyze_matra_distribution.py — Mātrā-count distribution of the Dhātupāṭha.

Aggregates the V1/V2-aware template distribution by total mātrā value.
Mātrā mapping per Pāṇinīya Śikṣā (see concepts/vyanjana_timing.md):

    C  = ½ mātrā
    V1 = 1 mātrā
    V2 = 2 mātrās

For each of the ~2,168 dhātus, the script reads the template label produced
by analyze_shells.py and sums the mātrā contribution across its tokens.

Outputs:
  data/derived/matra_distribution.csv — one row per mātrā value
  data/derived/matra_distribution.md  — human-readable summary with the
    templates contributing to each mātrā bucket
"""

from __future__ import annotations

import csv
import sys
from collections import defaultdict
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CSV_IN = REPO_ROOT / "data" / "derived" / "template_distribution.csv"
CSV_OUT = REPO_ROOT / "data" / "derived" / "matra_distribution.csv"
MD_OUT = REPO_ROOT / "data" / "derived" / "matra_distribution.md"


def template_to_matra(template: str) -> float:
    """Sum mātrā values across the C / V1 / V2 tokens in a template label.

    The template label uses two-character tokens for V1 and V2 and one-character
    C tokens (per the convention in scripts/analyze_shells.py).
    """
    i = 0
    matras = 0.0
    while i < len(template):
        if template[i:i+2] == "V1":
            matras += 1.0
            i += 2
        elif template[i:i+2] == "V2":
            matras += 2.0
            i += 2
        elif template[i] == "C":
            matras += 0.5
            i += 1
        else:
            i += 1
    return matras


def main() -> int:
    if not CSV_IN.exists():
        print(f"ERROR: input file not found at {CSV_IN}", file=sys.stderr)
        print("       Run scripts/analyze_shells.py first.", file=sys.stderr)
        return 1

    dist = defaultdict(int)
    template_breakdown = defaultdict(list)  # mātrā -> [(template, count), ...]
    total = 0

    with CSV_IN.open() as fh:
        reader = csv.DictReader(fh)
        for row in reader:
            template = row["template"]
            count = int(row["count"])
            m = template_to_matra(template)
            dist[m] += count
            template_breakdown[m].append((template, count))
            total += count

    sorted_matras = sorted(dist.keys())

    # Cumulative percentages
    rows = []
    cumulative = 0
    for m in sorted_matras:
        count = dist[m]
        pct = 100 * count / total
        cumulative += count
        cum_pct = 100 * cumulative / total
        rows.append((m, count, pct, cum_pct))

    # Write CSV
    CSV_OUT.parent.mkdir(parents=True, exist_ok=True)
    with CSV_OUT.open("w", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(["matra", "count", "percentage", "cumulative_pct"])
        for m, count, pct, cum_pct in rows:
            w.writerow([f"{m:.1f}", count, f"{pct:.2f}", f"{cum_pct:.2f}"])

    # Write markdown
    with MD_OUT.open("w") as fh:
        fh.write("# Dhātupāṭha — Mātrā Distribution\n\n")
        fh.write(f"> Source: aggregated from `template_distribution.csv` "
                 f"({total} dhātus).\n>\n")
        fh.write("> Mātrā per varṇa: C = ½, V1 = 1, V2 = 2 "
                 "(per Pāṇinīya Śikṣā; see `concepts/vyanjana_timing.md`).\n>\n")
        fh.write("> Generated by `scripts/analyze_matra_distribution.py`.\n\n")
        fh.write("---\n\n")

        fh.write("## Distribution by total mātrā\n\n")
        fh.write("| Mātrā | Count | % | Cum % |\n|---:|---:|---:|---:|\n")
        for m, count, pct, cum_pct in rows:
            fh.write(f"| {m:.1f} | {count} | {pct:.2f} | {cum_pct:.2f} |\n")

        # Cumulative threshold report
        fh.write("\n## Cumulative thresholds\n\n")
        thresholds = [50, 75, 80, 90, 95, 99]
        fh.write("How many mātrā buckets does it take to cover X% of the corpus?\n\n")
        fh.write("| Coverage | # of mātrā values | Last value added | Reached at |\n")
        fh.write("|---:|---:|---|---:|\n")
        cum_target = 0
        thr_idx = 0
        seen_thresholds = set()
        for i, (m, count, pct, cum_pct) in enumerate(rows, 1):
            while thr_idx < len(thresholds) and cum_pct >= thresholds[thr_idx]:
                if thresholds[thr_idx] not in seen_thresholds:
                    fh.write(f"| {thresholds[thr_idx]}% | {i} | "
                             f"**{m:.1f}** | {cum_pct:.2f}% |\n")
                    seen_thresholds.add(thresholds[thr_idx])
                thr_idx += 1

        fh.write("\n## Templates contributing to each mātrā value\n\n")
        for m in sorted_matras:
            templates_str = ", ".join(
                f"**{t}** ({c})"
                for t, c in sorted(template_breakdown[m], key=lambda x: -x[1])
            )
            fh.write(f"- **{m:.1f} mātrā** ({dist[m]} dhātus): {templates_str}\n")

    print(f"Wrote {CSV_OUT}")
    print(f"Wrote {MD_OUT}")
    print(f"Total: {total} dhātus across {len(sorted_matras)} distinct mātrā values")
    for m, count, pct, cum_pct in rows:
        print(f"  {m:>4.1f} mātrā: {count:>5d} ({pct:>5.2f}%)  cum {cum_pct:>5.2f}%")
    return 0


if __name__ == "__main__":
    sys.exit(main())
