#!/usr/bin/env python3
"""
analyze_matra_by_particle_count.py — Cross-tabulate dhātus by
(particle count, mātrā) to expose how the architecture uses
mātrā variation as a distinguishability axis on top of particle count.

Source: data/derived/template_distribution.csv (built by analyze_shells.py).

Outputs:
  data/derived/matra_by_particle_count.csv — long-form (particles, matra, count, …)
  data/derived/matra_by_particle_count.md  — human-readable cross-tab + per-bucket detail
"""

from __future__ import annotations

import csv
import sys
from collections import defaultdict
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CSV_IN  = REPO_ROOT / "data" / "derived" / "template_distribution.csv"
CSV_OUT = REPO_ROOT / "data" / "derived" / "matra_by_particle_count.csv"
MD_OUT  = REPO_ROOT / "data" / "derived" / "matra_by_particle_count.md"


def template_to_matra(template: str) -> float:
    """Sum mātrā values across C / V1 / V2 tokens (½ / 1 / 2 mātrā)."""
    i = 0
    m = 0.0
    while i < len(template):
        if template[i:i + 2] == "V1":
            m += 1.0
            i += 2
        elif template[i:i + 2] == "V2":
            m += 2.0
            i += 2
        elif template[i] == "C":
            m += 0.5
            i += 1
        else:
            i += 1
    return m


def main() -> int:
    if not CSV_IN.exists():
        print(f"ERROR: input not found at {CSV_IN}", file=sys.stderr)
        return 1

    # (particles, matra) -> aggregated info
    cell_count = defaultdict(int)
    cell_n_templates = defaultdict(int)
    cell_templates = defaultdict(list)   # list of (template, count)
    total = 0

    with CSV_IN.open() as fh:
        reader = csv.DictReader(fh)
        for row in reader:
            template = row["template"]
            particles = int(row["particles"])
            count = int(row["count"])
            matra = template_to_matra(template)
            key = (particles, matra)
            cell_count[key] += count
            cell_n_templates[key] += 1
            cell_templates[key].append((template, count))
            total += count

    sorted_keys = sorted(cell_count.keys())
    all_particles = sorted({p for (p, _) in sorted_keys})
    all_matras = sorted({m for (_, m) in sorted_keys})

    # CSV
    CSV_OUT.parent.mkdir(parents=True, exist_ok=True)
    with CSV_OUT.open("w", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(["particles", "matra", "count", "percentage", "n_templates"])
        for (p, m) in sorted_keys:
            count = cell_count[(p, m)]
            pct = 100 * count / total
            w.writerow([p, f"{m:.1f}", count, f"{pct:.2f}", cell_n_templates[(p, m)]])

    # Markdown
    with MD_OUT.open("w") as fh:
        fh.write("# Dhātupāṭha — Mātrā × Particle-Count Cross-Distribution\n\n")
        fh.write(f"> Source: aggregated from `template_distribution.csv` "
                 f"({total} dhātus).\n>\n")
        fh.write("> Mātrā per varṇa: C = ½, V1 = 1, V2 = 2 "
                 "(per Pāṇinīya Śikṣā).\n>\n")
        fh.write("> Generated by `scripts/analyze_matra_by_particle_count.py`.\n\n")
        fh.write("---\n\n")

        # Cross-tab grid
        fh.write("## Cross-tabulation (count of dhātus per (particles, mātrā) cell)\n\n")
        fh.write("| Particles \\ Mātrā |")
        for m in all_matras:
            fh.write(f" {m:.1f} |")
        fh.write(" **Total** | **# Mātrā buckets** |\n")
        fh.write("|---:|" + "---:|" * len(all_matras) + "---:|---:|\n")
        for p in all_particles:
            fh.write(f"| **{p}** |")
            row_total = 0
            n_buckets = 0
            for m in all_matras:
                count = cell_count.get((p, m), 0)
                if count:
                    row_total += count
                    n_buckets += 1
                    fh.write(f" {count} |")
                else:
                    fh.write(" — |")
            fh.write(f" **{row_total}** | **{n_buckets}** |\n")

        # Per-particle-count breakout
        fh.write("\n## Per particle count\n\n")
        for p in all_particles:
            ms_for_p = sorted({m for (pp, m) in sorted_keys if pp == p})
            count_for_p = sum(cell_count[(p, m)] for m in ms_for_p)
            n_templates = sum(cell_n_templates[(p, m)] for m in ms_for_p)
            min_m, max_m = min(ms_for_p), max(ms_for_p)
            span = max_m - min_m
            fh.write(f"### {p} particles — "
                     f"{count_for_p} dhātus, {n_templates} templates, "
                     f"{len(ms_for_p)} mātrā buckets ({min_m:.1f} – {max_m:.1f}, "
                     f"span {span:.1f})\n\n")
            fh.write("| Mātrā | Count | % | Templates |\n|---:|---:|---:|---|\n")
            for m in ms_for_p:
                count = cell_count[(p, m)]
                pct = 100 * count / count_for_p
                templates = ", ".join(
                    f"`{t}`({c})"
                    for t, c in sorted(cell_templates[(p, m)], key=lambda x: -x[1])
                )
                fh.write(f"| {m:.1f} | {count} | {pct:.1f}% | {templates} |\n")
            fh.write("\n")

    # Console summary
    print(f"Wrote {CSV_OUT}")
    print(f"Wrote {MD_OUT}")
    print(f"Total: {total} dhātus across {len(sorted_keys)} (particle, mātrā) cells")
    for p in all_particles:
        ms = sorted({m for (pp, m) in sorted_keys if pp == p})
        cnt = sum(cell_count[(p, m)] for m in ms)
        span = max(ms) - min(ms) if ms else 0
        print(f"  {p}-particle: {cnt} dhātus | "
              f"{len(ms)} mātrā buckets | "
              f"{min(ms):.1f}–{max(ms):.1f} | span {span:.1f}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
