#!/usr/bin/env python3
"""
analyze_racana_by_gana.py — Cross-tabulate dhātu-racanā templates ×
Pāṇinian gaṇa classifications.

For each of the ~2,168 dhātus in the Dhātupāṭha:
  1. Compute its racanā template via the V1/V2-aware classifier
     (reused from analyze_shells.py).
  2. Tag with the dhātu's documented gaṇa (from data/dhatupatha.csv).
  3. Build the (racanā × gaṇa) cross-tabulation.

The two classifications are independent in principle: *racanā* is a
phonetic-structural shape; *gaṇa* is the morphological-inflectional class
marked by the *vikaraṇa* signature. This script tests whether they
correlate empirically — does Pāṇini's documented classification show
phonetic-architectural concentration?

Outputs:
  data/derived/racana_by_gana.csv — full cross-tab (rows = racanā,
    columns = gaṇa 1–10, plus row total and column total)
  data/derived/racana_by_gana.md  — readable narrative:
    - top-10 racanāḥ × all 10 gaṇāḥ table with row/col percentages
    - per-gaṇa concentration (dominant racanā per gaṇa)
    - per-racanā concentration (dominant gaṇa per racanā)
"""

from __future__ import annotations

import csv
import sys
from collections import defaultdict
from pathlib import Path

# Reuse parsing logic
sys.path.insert(0, str(Path(__file__).parent))
from decompose_dhatupatha import (  # noqa: E402
    strip_markers, strip_anubandhas, GANA_NAMES,
)
from analyze_shells import classify_shell  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parent.parent
DATA_FILE = REPO_ROOT / "data" / "dhatupatha.csv"
CSV_OUT = REPO_ROOT / "data" / "derived" / "racana_by_gana.csv"
MD_OUT = REPO_ROOT / "data" / "derived" / "racana_by_gana.md"


# Top-10 racanāḥ in the §10.6 order, with their -ādi class names.
# Source: as_1_10_building_dhatuh.md §10.6 table.
TOP_TEN_RACANAS = [
    ("CV1C",   "gamādi",    "गमादि",    "2"),
    ("CCV1C",  "smarādi",   "स्मरादि",  "2½"),
    ("CV1CC",  "kalpādi",   "कल्पादि",  "2½"),
    ("CV2CV1", "bādhrādi",  "बाध्रादि", "4"),
    ("CV2C",   "vācādi",    "वाचादि",   "3"),
    ("CV2",    "dhādi",     "धादि",     "2½"),
    ("V1C",    "iṣādi",     "इषादि",    "1½"),
    ("CV1",    "krādi",     "क्रादि",   "1½"),
    ("CV1CV2", "cityādi",   "चित्यादि", "4"),
    ("CCV2",   "sthādi",    "स्थादि",   "3"),
]
TOP_TEN_TEMPLATES = [t[0] for t in TOP_TEN_RACANAS]
RACANA_NAME = {t[0]: f"{t[1]} ({t[2]})" for t in TOP_TEN_RACANAS}


def short_gana(gana: int) -> str:
    """Short label e.g. '1 bhvādi' for table headers."""
    full = GANA_NAMES.get(gana, f"gana-{gana}")
    # Use only the Roman name (no Devanagari) for narrow column headers.
    name = full.split(" (")[0]
    return f"{gana} {name}"


def main() -> int:
    if not DATA_FILE.exists():
        print(f"ERROR: data file not found at {DATA_FILE}", file=sys.stderr)
        return 1

    # (racanā, gaṇa) -> count
    cell = defaultdict(int)
    # racanā -> total across all gaṇas
    racana_total = defaultdict(int)
    # gaṇa -> total across all racanāḥ
    gana_total = defaultdict(int)
    total = 0

    with DATA_FILE.open() as fh:
        for row in csv.reader(fh):
            if len(row) < 3 or not row[0].isdigit():
                continue
            gana = int(row[0])
            original = row[2].strip()

            structural = strip_anubandhas(original)
            if not structural:
                continue
            racana = classify_shell(structural)
            if not racana:
                continue

            cell[(racana, gana)] += 1
            racana_total[racana] += 1
            gana_total[gana] += 1
            total += 1

    all_ganas = sorted(gana_total.keys())
    # All observed racanāḥ in descending count order
    sorted_racanas = sorted(racana_total.items(), key=lambda x: -x[1])

    # --- CSV: full cross-tab ---
    CSV_OUT.parent.mkdir(parents=True, exist_ok=True)
    with CSV_OUT.open("w", newline="") as fh:
        w = csv.writer(fh)
        header = ["racana", "name"] + [str(g) for g in all_ganas] + ["row_total"]
        w.writerow(header)
        for racana, total_for_racana in sorted_racanas:
            row = [racana, RACANA_NAME.get(racana, "")]
            for g in all_ganas:
                row.append(cell.get((racana, g), 0))
            row.append(total_for_racana)
            w.writerow(row)
        # column-total row
        w.writerow(["TOTAL", ""] + [gana_total[g] for g in all_ganas] + [total])

    # --- Markdown narrative ---
    with MD_OUT.open("w") as fh:
        fh.write("# Dhātupāṭha — *Racanā* × *Gaṇa* Cross-Distribution\n\n")
        fh.write(f"> Source: `data/dhatupatha.csv` ({total} dhātus across "
                 f"{len(sorted_racanas)} observed *racanāḥ* and "
                 f"{len(all_ganas)} *gaṇāḥ*).\n>\n")
        fh.write("> Generated by `scripts/analyze_racana_by_gana.py`.\n\n")
        fh.write("---\n\n")

        # --- Top-10 racanāḥ × all 10 gaṇāḥ ---
        fh.write("## Top-10 *racanāḥ* × *gaṇāḥ* (counts)\n\n")
        fh.write("Columns are gaṇas 1–10. Each row shows how a top-10 "
                 "*racanā* distributes across Pāṇini's inflectional classes.\n\n")
        # header
        fh.write("| Racanā | Class |")
        for g in all_ganas:
            fh.write(f" {g} |")
        fh.write(" **Total** |\n|---|---|")
        for _ in all_ganas:
            fh.write("---:|")
        fh.write("---:|\n")
        for racana, name, _, _ in TOP_TEN_RACANAS:
            fh.write(f"| **{racana}** | *{name}* |")
            for g in all_ganas:
                v = cell.get((racana, g), 0)
                fh.write(f" {v if v else '—'} |")
            fh.write(f" **{racana_total[racana]}** |\n")
        # column totals row, restricted to top-10
        fh.write("| **Top-10 column total** | |")
        for g in all_ganas:
            col_top10 = sum(cell.get((r, g), 0) for r in TOP_TEN_TEMPLATES)
            fh.write(f" **{col_top10}** |")
        fh.write(f" **{sum(racana_total[r] for r in TOP_TEN_TEMPLATES)}** |\n")
        # full gaṇa totals row
        fh.write("| **Gaṇa total (all racanāḥ)** | |")
        for g in all_ganas:
            fh.write(f" *{gana_total[g]}* |")
        fh.write(f" *{total}* |\n\n")

        # --- Same table as row-percent (within-racanā shares) ---
        fh.write("## Top-10 *racanāḥ* — within-row percentages\n\n")
        fh.write("How does each *racanā* distribute across the gaṇas? "
                 "(Each row sums to 100%.)\n\n")
        fh.write("| Racanā | Class |")
        for g in all_ganas:
            fh.write(f" {g} |")
        fh.write(" Total |\n|---|---|")
        for _ in all_ganas:
            fh.write("---:|")
        fh.write("---:|\n")
        for racana, name, _, _ in TOP_TEN_RACANAS:
            total_r = racana_total[racana]
            fh.write(f"| **{racana}** | *{name}* |")
            for g in all_ganas:
                v = cell.get((racana, g), 0)
                pct = 100 * v / total_r if total_r else 0
                fh.write(f" {pct:.1f}% |" if v else " — |")
            fh.write(f" **{total_r}** |\n")
        fh.write("\n")

        # --- Per-gaṇa concentration ---
        fh.write("## Per-*gaṇa* concentration — dominant *racanāḥ* per class\n\n")
        fh.write("For each *gaṇa*, the *racanāḥ* contributing the most "
                 "dhātus (top 3 + the *gaṇa*'s share of its top *racanā*).\n\n")
        fh.write("| Gaṇa | Name | Total dhātus | Top *racanā* (share within gaṇa) | "
                 "2nd | 3rd | Distinct *racanāḥ* | Top-3 share |\n")
        fh.write("|---:|---|---:|---|---|---|---:|---:|\n")
        for g in all_ganas:
            full = GANA_NAMES.get(g, f"gana-{g}")
            total_g = gana_total[g]
            racanas_in_gana = [(r, cell[(r, g)])
                               for r in racana_total
                               if cell.get((r, g), 0) > 0]
            racanas_in_gana.sort(key=lambda x: -x[1])
            top1 = racanas_in_gana[0] if racanas_in_gana else ("—", 0)
            top2 = racanas_in_gana[1] if len(racanas_in_gana) > 1 else ("—", 0)
            top3 = racanas_in_gana[2] if len(racanas_in_gana) > 2 else ("—", 0)
            top3_sum = sum(c for _, c in racanas_in_gana[:3])
            top3_share = 100 * top3_sum / total_g if total_g else 0

            def cell_label(t):
                r, c = t
                if r == "—":
                    return "—"
                pct = 100 * c / total_g if total_g else 0
                return f"{r} ({c}, {pct:.0f}%)"

            fh.write(f"| **{g}** | *{full}* | {total_g} | "
                     f"{cell_label(top1)} | {cell_label(top2)} | {cell_label(top3)} | "
                     f"{len(racanas_in_gana)} | {top3_share:.1f}% |\n")
        fh.write("\n")

        # --- Per-racanā concentration ---
        fh.write("## Per-*racanā* concentration — dominant *gaṇāḥ* per shape\n\n")
        fh.write("For each top-10 *racanā*, which *gaṇāḥ* concentrate the dhātus "
                 "of that shape.\n\n")
        fh.write("| Racanā | Class | Total | Top *gaṇa* | 2nd | 3rd | "
                 "Distinct *gaṇāḥ* | Top-3 share |\n")
        fh.write("|---|---|---:|---|---|---|---:|---:|\n")
        for racana, name, _, _ in TOP_TEN_RACANAS:
            total_r = racana_total[racana]
            ganas_in_racana = [(g, cell[(racana, g)])
                               for g in all_ganas
                               if cell.get((racana, g), 0) > 0]
            ganas_in_racana.sort(key=lambda x: -x[1])
            t1 = ganas_in_racana[0] if ganas_in_racana else (0, 0)
            t2 = ganas_in_racana[1] if len(ganas_in_racana) > 1 else (0, 0)
            t3 = ganas_in_racana[2] if len(ganas_in_racana) > 2 else (0, 0)
            top3_sum = sum(c for _, c in ganas_in_racana[:3])
            top3_share = 100 * top3_sum / total_r if total_r else 0

            def gcell(t):
                g, c = t
                if g == 0:
                    return "—"
                pct = 100 * c / total_r if total_r else 0
                name = GANA_NAMES.get(g, f"gana-{g}").split(" (")[0]
                return f"{g} *{name}* ({c}, {pct:.0f}%)"

            fh.write(f"| **{racana}** | *{name}* | {total_r} | "
                     f"{gcell(t1)} | {gcell(t2)} | {gcell(t3)} | "
                     f"{len(ganas_in_racana)} | {top3_share:.1f}% |\n")
        fh.write("\n")

        # --- Coverage summary ---
        top10_total = sum(racana_total[r] for r in TOP_TEN_TEMPLATES)
        fh.write("## Coverage summary\n\n")
        fh.write(f"- Total dhātus: **{total}**\n")
        fh.write(f"- Top-10 *racanāḥ* cover: **{top10_total} "
                 f"({100 * top10_total / total:.2f}%)**\n")
        fh.write(f"- Distinct *racanāḥ* observed: **{len(sorted_racanas)}**\n")
        fh.write(f"- *Gaṇāḥ* observed: **{len(all_ganas)}**\n")
        fh.write("- Cells (*racanā* × *gaṇa*) with at least one dhātu: "
                 f"**{len([k for k, v in cell.items() if v > 0])}** "
                 f"out of {len(sorted_racanas) * len(all_ganas)} possible.\n")

    # --- Console summary ---
    print(f"Wrote {CSV_OUT}")
    print(f"Wrote {MD_OUT}")
    print(f"Total: {total} dhātus across "
          f"{len(sorted_racanas)} racanāḥ × {len(all_ganas)} gaṇāḥ")
    print(f"Top-10 racanāḥ cover: {100 * sum(racana_total[r] for r in TOP_TEN_TEMPLATES) / total:.2f}%")
    return 0


if __name__ == "__main__":
    sys.exit(main())
