#!/usr/bin/env python3
"""per_corpus_productivity.py — Per-sub-corpus dhātu productivity rankings.

Companion to `cross_corpus.py`. Where cross_corpus.py focuses on top-20 names
and pairwise Spearman, this script produces detailed per-corpus rankings
(top-50) including counts and percentages, in a CSV form that's easy to
slice in spreadsheets or feed into figures.

Sub-corpora: same as cross_corpus.py
  - Ṛgveda (śruti)
  - Atharvaveda (Śaunaka) (śruti)
  - Mahābhārata (smriti)
  - Rāmāyaṇa (smriti)
  - Aṣṭāvakragīta (a smṛti gītā; thematic proxy while BhG ingest is pending)

Output: data/derived/per_corpus_productivity.csv
        data/derived/per_corpus_productivity.md (narrative)

Note on the Bhagavadgītā: BhG is excised from the DCS Mahābhārata dump
(canonical MBh 6.23-40 is absent). To get per-BhG rankings, a separate
ingest from GRETIL (or a Sanskrit Heritage Reader lemmatizer pass) is
required. See `bhagavadgita_ingest.py` (TODO) for the planned path.
"""
from __future__ import annotations
import csv
import sys
from collections import defaultdict
from pathlib import Path

# Reuse parse_subcorpus from cross_corpus.py
BUNDLE = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(BUNDLE / "scripts"))
from cross_corpus import (  # noqa: E402
    load_dictionary, parse_subcorpus, CONLLU_DIR, FULL_VALENCY,
)

OUT_CSV = BUNDLE / "data" / "derived" / "per_corpus_productivity.csv"
OUT_MD = BUNDLE / "data" / "derived" / "per_corpus_productivity.md"

SUB_CORPORA = [
    ("Ṛgveda", "śruti"),
    ("Atharvaveda (Śaunaka)", "śruti"),
    ("Mahābhārata", "smriti"),
    ("Rāmāyaṇa", "smriti"),
    ("Aṣṭāvakragīta", "smriti (gītā)"),  # BhG proxy — small but in DCS
]

TOP_N = 50


def main():
    print("Loading dictionary...", flush=True)
    dictionary = load_dictionary()
    print(f"  {len(dictionary):,} entries.", flush=True)

    # Full-corpus valency for comparison
    full_valency: dict[str, int] = {}
    with open(FULL_VALENCY, encoding="utf-8") as f:
        for row in csv.DictReader(f):
            full_valency[row["root"]] = int(row["valency_path_c"])

    # Per-corpus parse
    results = []
    for corpus_name, style in SUB_CORPORA:
        corpus_dir = CONLLU_DIR / corpus_name
        if not corpus_dir.exists():
            print(f"  SKIP {corpus_name}: directory not found.", flush=True)
            continue
        print(f"\nParsing {corpus_name}...", flush=True)
        pairs, totals, total_tokens, n_files = parse_subcorpus(corpus_dir, dictionary)
        valency = {root: len(pset) for root, pset in pairs.items()}
        results.append({
            "name": corpus_name,
            "style": style,
            "n_files": n_files,
            "total_tokens": total_tokens,
            "valency": valency,
            "tokens": dict(totals),
        })
        print(f"  {n_files} files | {total_tokens:,} verb tokens | "
              f"{len(valency):,} distinct roots.", flush=True)

    # --- CSV: long-form, one row per (corpus, rank, root, valency, tokens, pct) ---
    OUT_CSV.parent.mkdir(parents=True, exist_ok=True)
    with OUT_CSV.open("w", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(["corpus", "style", "rank", "root", "valency", "tokens",
                    "pct_of_corpus_tokens", "in_canonical_polyvalent"])
        canonical = {"kṛ", "bhū", "sthā", "gam", "jñā", "dā", "dhā", "nī", "hṛ"}
        for res in results:
            ranked = sorted(res["tokens"].items(), key=lambda kv: -kv[1])
            for rank, (root, tok) in enumerate(ranked[:TOP_N], 1):
                v = res["valency"].get(root, 0)
                pct = 100 * tok / res["total_tokens"] if res["total_tokens"] else 0
                w.writerow([res["name"], res["style"], rank, root, v, tok,
                            f"{pct:.2f}", "yes" if root in canonical else ""])

    # --- Markdown narrative ---
    with OUT_MD.open("w") as fh:
        fh.write("# Per-sub-corpus dhātu productivity rankings\n\n")
        fh.write("> Per-dhātu attestation counts and valency, ranked within each "
                 "DCS sub-corpus. Companion to `cross_corpus.py`.\n>\n")
        fh.write("> Generated by `scripts/per_corpus_productivity.py`.\n\n")
        fh.write("---\n\n")

        # Summary table
        fh.write("## Sub-corpus summary\n\n")
        fh.write("| Sub-corpus | Style | Files | Verb tokens | Distinct roots |"
                 " Top root (tokens, % of corpus) |\n|---|---|---:|---:|---:|---|\n")
        for res in results:
            ranked = sorted(res["tokens"].items(), key=lambda kv: -kv[1])
            if ranked:
                top_root, top_tok = ranked[0]
                top_pct = 100 * top_tok / res["total_tokens"]
                top_line = f"**{top_root}** ({top_tok:,}, {top_pct:.1f}%)"
            else:
                top_line = "—"
            fh.write(f"| {res['name']} | {res['style']} | {res['n_files']:,} | "
                     f"{res['total_tokens']:,} | {len(res['valency']):,} | "
                     f"{top_line} |\n")
        fh.write("\n")

        # Per-corpus top-20 rankings
        for res in results:
            fh.write(f"## {res['name']} *({res['style']})* — top 20 by token count\n\n")
            fh.write(f"Files: {res['n_files']:,} · Verb tokens: "
                     f"{res['total_tokens']:,} · Distinct roots: "
                     f"{len(res['valency']):,}\n\n")
            fh.write("| Rank | Root | Valency | Tokens | % of corpus | Canonical |\n")
            fh.write("|---:|---|---:|---:|---:|:---:|\n")
            ranked = sorted(res["tokens"].items(), key=lambda kv: -kv[1])
            canonical = {"kṛ", "bhū", "sthā", "gam", "jñā", "dā", "dhā", "nī", "hṛ"}
            cumulative_tokens = 0
            for rank, (root, tok) in enumerate(ranked[:20], 1):
                v = res["valency"].get(root, 0)
                pct = 100 * tok / res["total_tokens"]
                cumulative_tokens += tok
                mark = "●" if root in canonical else ""
                fh.write(f"| {rank} | **{root}** | {v} | {tok:,} | "
                         f"{pct:.2f}% | {mark} |\n")
            cum_pct = 100 * cumulative_tokens / res["total_tokens"]
            fh.write(f"\n*Top-20 cumulative: **{cumulative_tokens:,} verb tokens "
                     f"= {cum_pct:.1f}%** of this sub-corpus.*\n\n")

        # Canonical-9 coverage
        fh.write("## Canonical-9 polyvalent core across sub-corpora\n\n")
        fh.write("Tokens (and ranks) for the canonical compact-core dhātus:\n\n")
        canonical_list = ["kṛ", "bhū", "sthā", "gam", "jñā", "dā", "dhā", "nī", "hṛ"]
        # Column headers
        fh.write("| Root |")
        for res in results:
            fh.write(f" {res['name'][:14]} (tokens / rank) |")
        fh.write("\n|---|" + "---:|" * len(results) + "\n")
        for root in canonical_list:
            fh.write(f"| **{root}** |")
            for res in results:
                tok = res["tokens"].get(root, 0)
                ranked = sorted(res["tokens"].items(), key=lambda kv: -kv[1])
                rank = next((i + 1 for i, (r, _) in enumerate(ranked) if r == root),
                            None)
                if tok:
                    fh.write(f" {tok:,} / #{rank} |")
                else:
                    fh.write(" — |")
            fh.write("\n")
        fh.write("\n")

        # Notes on BhG
        fh.write("## On the Bhagavad Gītā\n\n")
        fh.write("The Bhagavad Gītā is **not present** in the DCS Mahābhārata "
                 "dump (the canonical BhG range — MBh 6.23–40 — is absent from "
                 "the conllu files). To extend this analysis to the Gītā "
                 "specifically, a separate ingest path is needed:\n\n")
        fh.write("1. **GRETIL plain text** (`https://gretil.sub.uni-goettingen.de/`) "
                 "+ a lemmatization pass via INRIA Sanskrit Heritage Reader or "
                 "`sanskrit_parser`.\n")
        fh.write("2. **Vedabase / iskcon-desire-tree word-by-word** data — "
                 "lemma + grammatical form already tagged; format conversion "
                 "to CoNLL-U is straightforward.\n")
        fh.write("3. **Custom hand-tagging** of the 700 BhG verses — feasible "
                 "by one person in a few days; smaller corpus than other "
                 "DCS texts.\n\n")
        fh.write("`Aṣṭāvakragīta` (~298 verses) is included above as a "
                 "**thematic proxy** since DCS has it. It is a different text "
                 "but shares the *gītā* genre and yields a comparable signature.\n")

    print(f"\nWrote {OUT_CSV}")
    print(f"Wrote {OUT_MD}")


if __name__ == "__main__":
    main()
